services:
  backend:
    build: ./backend
    ports:
      - "1323:1323"
    env_file: 
      - backend/.env
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - echofy-net

  frontend:
    build: 
      context: ./frontend
    env_file: 
      - frontend/.env
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - echofy-net

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - echofy-net

volumes:
  redis_data:

networks:
  echofy-net:
    name: echofy-shared-network
    driver: bridge
